/*
 * SURVEY
 */

/*
 * SURVEY ELIGIBILITY RADIO BUTTON ID
 */
export const ELIGIBILITY_OPTION_ALLSTORE_ID = 1;
export const ELIGIBILITY_OPTION_SEGMENTATION_ID = 3;
export const ELIGIBILITY_OPTION_DIRECTSTORE_ID = 2;

export const SURVEY_STATUS_REJECTED = 'rejected';
export const SURVEY_STATUS_PENDING = 'pending';
export const SURVEY_STATUS_APPROVED = 'approved';
